const actionNames = {
  SELECT_COUNTRY: 'SELECT_COUNTRY',
  SELECT_COUNTRY_FROM_URL: 'SELECT_COUNTRY_FROM_URL',
  GET_COUNTRIES: 'GET_COUNTRIES',
  SELECT_RETAILER: 'SELECT_RETAILER',
  GET_RETAILERS: 'GET_RETAILERS',
  EMPTY_RETAILERS_LIST: 'EMPTY_RETAILERS_LIST',
  GET_AUTH: 'GET_AUTH'
};

export default actionNames;
